### ISSUE TITLE
Wiris plugin with Froala

### ISSUE THREAD

**Issue by javeriaanwer** [wiris/test-word-addins#1]
hi,

I am using Wiris plugin with froala editor, I want to perform some task when wiris formula is integrated in froala editor, apparently i am not getting this by froala's events such as contentChanged or html.set, I am wondering if you provide your own event on accept button click, where can I find that?

Regards,
Javeria

**Comment by wirismath** [comment]
In the configuration.ini file you need to set wirislisteners=true.

Using wrs_addPluginListener you can add a listener before and after creating a formula.
The generic way of adding a listener is wrs_addPluginListener({'listener': callback(param){}}); 
The two listeners we currently have are onBeforeFormulaInsertion and onAfterFormulaIntertion.
The first one is triggered before updating a formula and the second one after updating it

onBeforeFormulaInsertion:
wrs_addPluginListener({'onBeforeFormulaInsertion': function(params) { ....}});
The parameters available in the callback are: mathml, editMode, wirisProperties and language. 

For example, if you needed to save the MathML somewhere before rendering the image you could do the following:
wrs_addPluginListener({'onBeforeFormulaInsertion', :   function(params){
      saveMathml(params.mathml);
}});

onAfterFormulaInsertion:
wrs_addPluginListener({'onAfterFormulaInsertion': function(params) { ....}});

The parameters avaible in the callback are node (the image or Latex generated) or editMode.
For example, if you needed to save the generated image somewhere:

wrs_addPluginListener({'onAfterFormulaInsertion', :   function(params){
      saveImage(params.node);
}});

The documentation on this should be available online at http://www.wiris.com/plugins/jsdoc/ but we have had a minor issue. It should be back online shortly.
