### ISSUE TITLE
Wiris hosting issue

### ISSUE THREAD

**Issue by javeriaanwer** [wiris/test-word-addins#2]
Hi,

I am using Wiris with froala, I don't want to host wiris application on my server, as my own application is hosting on a server, how can I use wrirs application without hosting it?

Regards,
Javeria

**Comment by wirismath** [comment]
WIRIS plugins by default use the services hosted at www.wiris.net. You can install WIRIS services on your server if you purchase a license. For the details on the server components license you should contact sales@wiris.com.
